# Generated by Django 6.0.6 on 2026-07-30 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('area', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مساحت')),
                ('descreaption', models.TextField(verbose_name='توضیحات')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 0 شروع شود و 11 رقم باشد', regex='^0\\d{10}$')], verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
